blank_issues_enabled: false
contact_links:
  - name: ðŸ“– Documentation
    url: https://github.com/Lajuro/exaroton-servers/tree/main/docs
    about: Check the documentation before opening an issue
  - name: ðŸ’¬ Discussions
    url: https://github.com/Lajuro/exaroton-servers/discussions
    about: Ask questions and share ideas in Discussions
